mygadgets/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include

urlpatterns = (
    [
    path('admin/', admin.site.urls),
    path("", include("user.urls", namespace="user")),
  
    # path("tinymce/", include("tinymce.urls")),
    
]
    + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
)
admin.site.site_header = "ecom Administration"
admin.site.site_title = "ecom Admin Portal"
admin.site.index_title = "Welcome to ecom Admin Portal"

user/urls.py
from django.urls import path
from . import views

app_name = "user"

urlpatterns = [
    path("about-us", views.about_us, name="about_us"),
    path("cart/<int:id>", views.addtocart, name="addtocart"),
    path("cart", views.viewcart, name="viewcart"),
    path("checkout", views.checkout, name="checkout"),
    path("coming-soon", views.coming_soon, name="coming_soon"),
    path("contact-us", views.contact_us, name="contact_us"),
    path("faq", views.faq, name="faq"),
    path("forgot", views.forget_password, name="forgot password"),
    path('change password/<token>/', views.change_password, name="change password"),
    path("delete/<int:id>", views.deletefromwishlist, name="deletefromwishlist"),
    path("deletecart/<int:id>", views.deletefromcart, name="deletefromcart"),
    path("", views.index, name="index"),
    path("login", views.login_views, name="login"),
    path("logout", views.logout_view, name="logout"),
    path("order--success", views.order_success2, name="order__success"),
    path("order-tracking", views.order_tracking, name="order_tracking"),
    path("otp", views.otp, name="otp"),
    path("product/<int:id>", views.product, name="product"),
    path("search", views.search, name="search"),
    path("seller-dashboard", views.seller_dashboard, name="seller_dashboard"),
    path("shop-category/<int:id>", views.shop_category, name="shop_category"),
    path("shop/<int:id>", views.shop, name="shop"),
    path("sign-up", views.user_register, name="sign_up"),
    path("dashboard", views.user_dashboard, name="dashboard"),
    path("wishlist/<int:id>", views.addtowishlist, name="addtowishlist"),
    path("wishlist",views.viewwishlist,name="viewwishlist"),
    path("404", views.error_404, name="error_404"),
    
    # cart add ajax
    path("addquantity/",views.addQuantity, name="addquantity"),
    path("lessquantity/",views.lessQuantity,name="lessquantity"),
    
    # payment
    path("payment/", views.order_payment, name="payment"),
    path("order_success/", views.callback, name="order_success"),
]

templates/web/login.html
{% extends 'web/partials/base2.html' %}

{% load static %}

{% block content %}
    <!-- Header End -->

    <!-- mobile fix menu start -->
    <div class="mobile-menu d-md-none d-block mobile-cart">
        <ul>
            <li class="active">
                <a href="/">
                    {% comment %} <i class="iconly-Home icli"></i> {% endcomment %}
                    <span class="material-symbols-outlined">
                        home
                        </span>
                    <span>Home</span>
                </a>
            </li>

            <li class="mobile-category">
                <a href="javascript:void(0)">
                    {% comment %} <i class="iconly-Category icli js-link"></i> {% endcomment %}
                    <span class="material-symbols-outlined">
                        category
                        </span>
                    <span>Category</span>
                </a>
            </li>

            <li>
                <a href="{% url 'user:search' %}" class="search-box">
                    {% comment %} <i class="iconly-Search icli"></i> {% endcomment %}
                    <span class="material-symbols-outlined">
                        search
                        </span>
                    <span>Search</span>
                </a>
            </li>

            <li>
                <a href="{% url 'user:viewwishlist' %}">
                    {% comment %} <i class="iconly-Heart icli"></i> {% endcomment %}
                    <span class="material-symbols-outlined">
                        favorite
                        </span>
                    <span>My Wish</span>
                </a>
            </li>

            <li>
                <a href="{% url 'user:viewcart' %}">
                    {% comment %} <i class="iconly-Bag-2 icli fly-cate"></i> {% endcomment %}
                    <span class="material-symbols-outlined">
                        shopping_cart
                        </span>
                    <span>Cart</span>
                </a>
            </li>
        </ul>
    </div>
    <!-- mobile fix menu end -->

    <!-- Breadcrumb Section Start -->
    <section class="breadscrumb-section pt-0">
        <div class="container-fluid-lg">
            <div class="row">
                <div class="col-12">
                    <div class="breadscrumb-contain">
                        <h2 class="mb-2">Log In</h2>
                        {% comment %} <nav>
                            <ol class="breadcrumb mb-0">
                                <li class="breadcrumb-item">
                                    <a href="/">
                                        <i class="fa fa-2x fa-solid fa-house"></i>
                                    </a>
                                </li>
                                <li class="breadcrumb-item active">Log In</li>
                            </ol>
                        </nav> {% endcomment %}
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Breadcrumb Section End -->

    <!-- log in section start -->
    <section class="log-in-section background-image-2 section-b-space">
        <div class="container-fluid-lg w-100">
            <div class="row">
                <div class="col-xxl-6 col-xl-5 col-lg-6 d-lg-block d-none ms-auto">
                    <div class="image-contain">
                        <img src="https://themes.pixelstrap.com/fastkart/assets/images/inner-page/log-in.png"
                            class="img-fluid" alt="">
                    </div>
                </div>

                <div class="col-xxl-4 col-xl-5 col-lg-6 col-sm-8 mx-auto">
                    <div class="log-in-box">
                        <div class="log-in-title">
                            <h3>Welcome To Fastkart</h3>
                            <h4>Log In Your Account</h4>
                        </div>

                        <div class="input-box">               
                            <form class="row g-4" method="POST">
                                {% csrf_token %}
                                <div class="col-12">
                                    <div class="form-floating theme-form-floating log-in-form">
                                        <input type="text" class="form-control" id="username" name="uname" placeholder="Phone Number">
                                        <label for="phone_number">Username</label>
                                    </div>
                                </div>

                                <div class="col-12">
                                    <div class="form-floating theme-form-floating log-in-form">
                                        <input type="password" class="form-control" id="password" name = "pass"
                                            placeholder="Password">
                                        <label for="password">Password</label>
                                    </div>
                                </div>

                                <div class="col-12">
                                    <div class="forgot-box">
                                        <div class="form-check ps-0 m-0 remember-box">
                                            <input class="checkbox_animated check-box" type="checkbox"
                                                id="flexCheckDefault">
                                            <label class="form-check-label" for="flexCheckDefault">Remember me</label>
                                        </div>
                                        <a href="{% url 'user:forgot password' %}" class="forgot-password">Forgot Password?</a>
                                    </div>
                                </div>

                                <div class="col-12">
                                    <button class="btn btn-animation w-100 justify-content-center" type="submit">Log
                                        In</button>
                                </div>
                            </form>
                        </div>
{% comment %} 
                        <div class="other-log-in">
                            <h6>or</h6>
                        </div>

                        <div class="log-in-button">
                            <ul>
                                <li>
                                    <a href="https://www.google.com/" class="btn google-button w-100">
                                        <img src="https://themes.pixelstrap.com/fastkart/assets/images/inner-page/google.png"
                                            class="blur-up lazyload" alt=""> Log In with Google
                                    </a>
                                </li>
                                <li>
                                    <a href="https://www.facebook.com/" class="btn google-button w-100">
                                        <img src="https://themes.pixelstrap.com/fastkart/assets/images/inner-page/facebook.png"
                                            class="blur-up lazyload" alt=""> Log In with Facebook
                                    </a>
                                </li>
                            </ul>
                        </div> {% endcomment %}

                        <div class="other-log-in">
                            <h6></h6>
                        </div>

                        <div class="sign-up-box">
                            <h4>Don't have an account?</h4>
                            <a href="{%url 'user:sign_up' %}">Sign Up</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- log in section end -->

    <!-- Footer Section Start -->
   
    <!-- Footer Section End -->

  

    <!-- Bg overlay Start -->
    <div class="bg-overlay"></div>
    <!-- Bg overlay End -->

    <!-- latest jquery-->
    <script src="https://themes.pixelstrap.com/fastkart/assets/js/jquery-3.6.0.min.js"></script>

    <!-- Bootstrap js-->
    <script src="https://themes.pixelstrap.com/fastkart/assets/js/bootstrap/bootstrap.bundle.min.js"></script>
    <script src="https://themes.pixelstrap.com/fastkart/assets/js/bootstrap/popper.min.js"></script>

    <!-- feather icon js-->
    <script src="https://themes.pixelstrap.com/fastkart/assets/js/feather/feather.min.js"></script>
    <script src="https://themes.pixelstrap.com/fastkart/assets/js/feather/feather-icon.js"></script>

    <!-- Slick js-->
    <script src="https://themes.pixelstrap.com/fastkart/assets/js/slick/slick.js"></script>
    <script src="https://themes.pixelstrap.com/fastkart/assets/js/slick/slick-animation.min.js"></script>
    <script src="https://themes.pixelstrap.com/fastkart/assets/js/slick/custom_slick.js"></script>

    <!-- Lazyload Js -->
    <script src="https://themes.pixelstrap.com/fastkart/assets/js/lazysizes.min.js"></script>

    <!-- script js -->
    <script src="https://themes.pixelstrap.com/fastkart/assets/js/script.js"></script>

    <!-- thme setting js -->
    <script src="https://themes.pixelstrap.com/fastkart/assets/js/theme-setting.js"></script>
</body>


<!-- Mon, 07 Nov 2022 10:09:26 GMT -->

</html>

{% endblock %}

templates/web/shop-left-sidebar.html
{% extends 'web/partials/base.html' %}

{% load static %}

{% block content %}

    <!-- mobile fix menu start -->
    <div class="mobile-menu d-md-none d-block mobile-cart">
        <ul>
            <li class="active">
                <a href="/">
                    {% comment %} <i class="iconly-Home icli"></i> {% endcomment %}
                    <span class="material-symbols-outlined">
                        home
                        </span>
                    <span>Home</span>
                </a>
            </li>

            <li class="mobile-category">
                <a href="javascript:void(0)">
                    {% comment %} <i class="iconly-Category icli js-link"></i> {% endcomment %}
                    <span class="material-symbols-outlined">
                        category
                        </span>
                    <span>Category</span>
                </a>
            </li>

            <li>
                <a href="{% url 'user:search' %}" class="search-box">
                    {% comment %} <i class="iconly-Search icli"></i> {% endcomment %}
                    <span class="material-symbols-outlined">
                        search
                        </span>
                    <span>Search</span>
                </a>
            </li>

            <li>
                <a href="{% url 'user:viewwishlist' %}">
                    {% comment %} <i class="iconly-Heart icli"></i> {% endcomment %}
                    <span class="material-symbols-outlined">
                        favorite
                        </span>
                    <span>My Wish</span>
                </a>
            </li>

            <li>
                <a href="{% url 'user:viewcart' %}">
                    {% comment %} <i class="iconly-Bag-2 icli fly-cate"></i> {% endcomment %}
                    <span class="material-symbols-outlined">
                        shopping_cart
                        </span>
                    <span>Cart</span>
                </a>
            </li>
        </ul>
    </div>
    <!-- mobile fix menu end -->

    <!-- Breadcrumb Section Start -->
    <section class="breadscrumb-section pt-0">
        <div class="container-fluid-lg">
            <div class="row">
                <div class="col-12">
                    <div class="breadscrumb-contain">
                        <h2>Shop Your Favourite</h2>
                        {% comment %} <nav>
                            <ol class="breadcrumb mb-0">
                                <li class="breadcrumb-item">
                                    <a href="/">
                                        <i class="fa fa-2x fa-solid fa-house"></i>
                                    </a>
                                </li>
                                <li class="breadcrumb-item active" aria-current="page">Shop Left Sidebar</li>
                            </ol>
                        </nav> {% endcomment %}
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Breadcrumb Section End -->

    <!-- Poster Section Start -->
   
    <!-- Shop Section Start -->
    <section class="section-b-space shop-section ">
        <div class="container-fluid-lg">
            <div class="row">
                    {% if messages %}
                        {% for message in messages %}
                            <div class="alert alert-info">
                                {{message}}
                            </div>
                        {% endfor %}
                    {% endif %}
                    <div class="row g-sm-4 g-3 product-list-section mt-3">
                        {% for product in category.get_products%}
                        <div class="col-lg-4 col-6 px-0">                                       
                                        <div class="product-box" style="border-right:0px;">
                                            <div class="product-image">
                                                <a href={% url 'user:product' product.id %}>
                                                    <img src="{{product.image.url}}"
                                                            class="img-fluid blur-up lazyload" alt="">
                                                </a>
                                                <ul class="product-option">
                                                    <li data-bs-toggle="tooltip" data-bs-placement="top"
                                                                title="View">
                                                                <a href="{% url 'user:product' product.id %}">
                                                                    <i data-feather="eye"></i>
                                                            </a>
                                                    </li>
                                                    <li data-bs-toggle="tooltip" data-bs-placement="top"
                                                                title="Wishlist">
                                                        <a href="{% url 'user:addtowishlist' product.id %}">
                                                            <i data-feather="heart"></i>
                                                        </a>
                                                        </li>
                                                </ul>
                                            </div>
                                            <div class="product-detail">
                                                <a href={% url 'user:product' product.id %}>
                                                            <h6 class="name">{{product.product}}</h6>
                                                </a>
                                                <h5 class="sold text-content">
                                                    {% if product.offer_price %}
                                                        <span class="theme-color price">Rs {{product.offer_price}}</span>
                                                            <del>{{product.price}}</del>
                                                    {% else %}
                                                    <span class="theme-color price">Rs {{product.price}}</span>
                                                    {% endif %}
                                                </h5>
                                                {% comment %} <div class="product-rating mt-sm-2 mt-1">
                                                        <ul class="rating">
                                                            <li>
                                                                <i data-feather="star" class="fill"></i>
                                                            </li>
                                                            <li>
                                                                <i data-feather="star" class="fill"></i>
                                                            </li>
                                                            <li>
                                                                <i data-feather="star" class="fill"></i>
                                                            </li>
                                                            <li>
                                                                <i data-feather="star" class="fill"></i>
                                                            </li>
                                                            <li>
                                                                <i data-feather="star"></i>
                                                            </li>
                                                        </ul>
    
                                                        <h6 class="theme-color">In Stock</h6>
                                                </div> {% endcomment %}
                                                <div class="add-to-cart-box">
                                                    {% if product.quantity > 0%}
                                                    <a href="{% url 'user:addtocart' product.id %}">
                                                        <button class="btn btn-add-cart">Add To Cart</button>
                                                    </a>  
                                                    {% else %}  
                                                    <a>
                                                        <button class="btn btn-add-cart">Out Of Stock </button>
                                                    </a>  
                                                    {% endif %}                                 
                                                </div>
                                            </div>
                                        </div>                                        
                                    </div>
                        {% endfor %}
                       
                    </div>
                        
                {% comment %}
                    <div class="row g-sm-4 g-3">
                        {% for product in products %}
                        <div class="col-xxl-3 col-lg-4 col-sm-6">
                            <img src="{{product.image.url}}" class="bg-img blur-up lazyload" alt="">
                            <div class="banner-details">
                                <div class="banner-box">
                                    <h6 class="text-danger">5% OFF</h6>
                                    <h5>Hot Deals on New Items</h5>
                                    <h6 class="text-content">Daily Essentials Eggs & Dairy</h6>
                                </div>
                                <a href="shop-left-sidebar.html" class="banner-button text-white">Shop Now <i
                                        class="fa-solid fa-right-long ms-2"></i></a>
                            </div>
                        </div>
                        
                        {% endfor %}
                    </div>
                {% endcomment %}
                    
                    <nav class="custome-pagination">
                        <ul class="pagination justify-content-center">
                            <li class="page-item disabled">
                                <a class="page-link" href="javascript:void(0)" tabindex="-1" aria-disabled="true">
                                    <i class="fa-solid fa-angles-left"></i>
                                </a>
                            </li>
                            <li class="page-item active">
                                <a class="page-link" href="javascript:void(0)">1</a>
                            </li>
                            <li class="page-item" aria-current="page">
                                <a class="page-link" href="javascript:void(0)">2</a>
                            </li>
                            <li class="page-item">
                                <a class="page-link" href="javascript:void(0)">3</a>
                            </li>
                            <li class="page-item">
                                <a class="page-link" href="javascript:void(0)">
                                    <i class="fa-solid fa-angles-right"></i>
                                </a>
                            </li>
                        </ul>
                    </nav>
                </div>
            </div>

        </div>
    </section>

 
    <!-- Shop Section End -->



    

    <!-- Add to cart Modal Start -->
    {% comment %} <div class="add-cart-box">
        <div class="add-iamge">
            <img src="https://themes.pixelstrap.com/fastkart/assets/images/cake/pro/1.jpg"
                class="img-fluid blur-up lazyload" alt="">
        </div>

        <div class="add-contain">
            <h6>Added to Cart</h6>
        </div>
    </div> {% endcomment %}
    <!-- Add to cart Modal End -->

  

   

<!-- shop-left-sidebar.html by HTTrack Website Copier/3.x [XR&CO'2014], Mon, 07 Nov 2022 10:09:25 GMT -->

</html>


{% endblock %}