mygadgets/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include

urlpatterns = (
    [
    path('admin/', admin.site.urls),
    path("", include("user.urls", namespace="user")),
  
    # path("tinymce/", include("tinymce.urls")),
    
]
    + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
)
admin.site.site_header = "ecom Administration"
admin.site.site_title = "ecom Admin Portal"
admin.site.index_title = "Welcome to ecom Admin Portal"

user/urls.py
from django.urls import path
from . import views

app_name = "user"

urlpatterns = [
    path("about-us", views.about_us, name="about_us"),
    path("cart/<int:id>", views.addtocart, name="addtocart"),
    path("cart", views.viewcart, name="viewcart"),
    path("checkout", views.checkout, name="checkout"),
    path("coming-soon", views.coming_soon, name="coming_soon"),
    path("contact-us", views.contact_us, name="contact_us"),
    path("faq", views.faq, name="faq"),
    path("forgot", views.forget_password, name="forgot password"),
    path('change password/<token>/', views.change_password, name="change password"),
    path("delete/<int:id>", views.deletefromwishlist, name="deletefromwishlist"),
    path("deletecart/<int:id>", views.deletefromcart, name="deletefromcart"),
    path("", views.index, name="index"),
    path("login", views.login_views, name="login"),
    path("logout", views.logout_view, name="logout"),
    path("order--success", views.order_success2, name="order__success"),
    path("order-tracking", views.order_tracking, name="order_tracking"),
    path("otp", views.otp, name="otp"),
    path("product/<int:id>", views.product, name="product"),
    path("search", views.search, name="search"),
    path("seller-dashboard", views.seller_dashboard, name="seller_dashboard"),
    path("shop-category/<int:id>", views.shop_category, name="shop_category"),
    path("shop/<int:id>", views.shop, name="shop"),
    path("sign-up", views.user_register, name="sign_up"),
    path("dashboard", views.user_dashboard, name="dashboard"),
    path("wishlist/<int:id>", views.addtowishlist, name="addtowishlist"),
    path("wishlist",views.viewwishlist,name="viewwishlist"),
    path("404", views.error_404, name="error_404"),
    
    # cart add ajax
    path("addquantity/",views.addQuantity, name="addquantity"),
    path("lessquantity/",views.lessQuantity,name="lessquantity"),
    
    # payment
    path("payment/", views.order_payment, name="payment"),
    path("order_success/", views.callback, name="order_success"),
]

templates/web/partials/footer.html
{% load static %}

<footer class="section-t-space">
    <div class="container-fluid-lg">
        <div class="service-section">
            <div class="row g-3">
                <div class="col-12">
                    <div class="service-contain">
                        <div class="service-box">
                            <div class="service-image">
                                <img src="{% static 'web/svg/product.svg' %} "
                                    class="blur-up lazyload" alt="">
                            </div>

                            <div class="service-detail">
                                <h5>Every Fresh Products</h5>
                            </div>
                        </div>

                        <div class="service-box">
                            <div class="service-image">
                                <img src="{% static 'web/svg/delivery.svg' %}"
                                    class="blur-up lazyload" alt="">
                            </div>

                            <div class="service-detail">
                                <h5>Free Delivery For Order Over $50</h5>
                            </div>
                        </div>

                        <div class="service-box">
                            <div class="service-image">
                                <img src="{% static 'web/svg/discount.svg' %}"
                                    class="blur-up lazyload" alt="">
                            </div>

                            <div class="service-detail">
                                <h5>Daily Mega Discounts</h5>
                            </div>
                        </div>

                        <div class="service-box">
                            <div class="service-image">
                                <img src="{% static 'web/svg/market.svg' %}"
                                    class="blur-up lazyload" alt="">
                            </div>

                            <div class="service-detail">
                                <h5>Best Price On The Market</h5>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="main-footer section-b-space section-t-space">
            <div class="row g-md-4 g-3">
                <div class="col-xl-3 col-lg-4 col-sm-6">
                    <div class="footer-logo">
                        <div class="theme-logo">
                            <a href="/">
                                <img src="{% static 'web/images/images/my furniture.png' %}"
                                    class="blur-up lazyload" alt="">
                            </a>
                        </div>

                        <div class="footer-logo-contain">
                            <p>We are a friendly bar serving a variety of cocktails, wines and beers. Our bar is a
                                perfect place for a couple.</p>

                            <ul class="address">
                                <li>
                                    <i data-feather="home"></i>
                                    <a href="javascript:void(0)">Near Calicut International Airport</a>
                                    
                                </li>
                                <li>
                                    <h5>+917356978603</h5>
                                </li>
                                <li>
                                    <i data-feather="mail"></i>
                                    {% comment %} <a href=gedexo.com>info@gedexo.com</a> {% endcomment %}
                                    <a href="mailto:info@gedexo.com" target="_blank" rel="noreferrer" class="ml-2">info@gedexo.com</a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>

                <div class="col-xl-2 col-lg-3 col-md-4 col-sm-6">
                    {% comment %} <div class="footer-title">
                        <h4>Categories</h4>
                    </div> {% endcomment %}

                    {% comment %} <div class="footer-contain">
                        <ul>
                            <li>
                                <a href="" class="text-content">Vegetables & Fruit</a>
                            </li>
                            <li>
                                <a href="" class="text-content">Beverages</a>
                            </li>
                            <li>
                                <a href="" class="text-content">Meats & Seafood</a>
                            </li>
                            <li>
                                <a href="" class="text-content">Frozen Foods</a>
                            </li>
                            <li>
                                <a href="" class="text-content">Biscuits & Snacks</a>
                            </li>
                            <li>
                                <a href="" class="text-content">Grocery & Staples</a>
                            </li>
                        </ul>
                    </div> {% endcomment %}
                </div>

                <div class="col-xl col-lg-2 col-sm-3">
                    <div class="footer-title">
                        <h4>Useful Links</h4>
                    </div>

                    <div class="footer-contain">
                        <ul>
                            <li>
                                <a href="/" class="text-content">Home</a>
                            </li>
                            <li>
                                <a href="{% url 'user:search' %}" class="text-content">Search</a>
                            </li>
                            {% comment %} <li>
                                <a href="{% url 'user:shop' 0 %}" class="text-content">Shop</a>
                            </li>
                            <li>
                                <a href="{% url 'user:about_us' %}" class="text-content">About Us</a>
                            </li>
                           
                            <li>
                                <a href="{% url 'user:contact_us' %}" class="text-content">Contact Us</a>
                            </li> {% endcomment %}
                        </ul>
                    </div>
                </div>

                <div class="col-xl-2 col-sm-3">
                    <div class="footer-title">
                        <h4>Help Center</h4>
                    </div>

                    <div class="footer-contain">
                        <ul>
                            {% comment %} <li>
                                <a href="{% url 'user:order_success' %}" class="text-content">Your Order</a>
                            </li>
                            <li>
                                <a href="{% url 'user:dashboard' %}" class="text-content">Your Account</a>
                            </li>
                            <li>
                                <a href="{% url 'user:order_tracking' %}" class="text-content">Track Order</a>
                            </li> {% endcomment %}
                            <li>
                                <a href="{% url 'user:viewwishlist' %}" class="text-content">Your Wishlist</a>
                            </li>
                            
                            <li>
                                <a href="{% url 'user:viewcart' %}" class="text-content">Your Cart</a>
                            </li>
                            {% comment %} <li>
                                <a href="{% url 'user:faq' %}" class="text-content">FAQ</a>
                            </li> {% endcomment %}
                        </ul>
                    </div>
                </div>

                <div class="col-xl-3 col-lg-4 col-sm-6">
                    <div class="footer-title">
                        <h4>Contact Us</h4>
                    </div>

                    <div class="footer-contact">
                        <ul>
                            <li>
                                <div class="footer-number">
                                    <i data-feather="phone"></i>
                                    <div class="contact-number">
                                        <h6 class="text-content">Near Calicut International Airport</h6>
                                        <h5>+917356978603</h5>
                                    </div>
                                </div>
                            </li>

                            <li>
                                <div class="footer-number">
                                    <i data-feather="mail"></i>
                                    <div class="contact-number">
                                        <h6 class="text-content">Email Address :</h6>
                                        <h5>info@gedexo.com</h5>
                                    </div>
                                </div>
                            </li>

                            <li class="social-app mb-0">
                                <h5 class="mb-2 text-content">Download App :</h5>
                                <ul>
                                    <li class="mb-0">
                                        <a href="https://play.google.com/store/apps" target="_blank">
                                            <img src="{% static 'web/images/playstore.svg' %}"
                                                class="blur-up lazyload" alt="">
                                        </a>
                                    </li>
                                    <li class="mb-0">
                                        <a href="https://www.apple.com/in/app-store/" target="_blank">
                                            <img src="{% static 'web/images/appstore.svg' %}"
                                                class="blur-up lazyload" alt="">
                                        </a>
                                    </li>
                                </ul>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>

        <div class="sub-footer section-small-space">
            <div class="reserve">
                <h6 class="text-content">©2022 Gedexo Technologies LLP All rights reserved</h6>
            </div>

            <div class="payment">
                <img src="{% static 'web/images/payment/1.png' %}"
                    class="blur-up lazyload" alt="">
            </div>

            <div class="social-link">
                <h6 class="text-content">Stay connected :</h6>
                <ul>
                    <li>
                        <a href="https://www.facebook.com/" target="_blank">
                            <i class="fa-brands fa-facebook-f"></i>
                        </a>
                    </li>
                    <li>
                        <a href="https://twitter.com/" target="_blank">
                            <i class="fa-brands fa-twitter"></i>
                        </a>
                    </li>
                    <li>
                        <a href="https://www.instagram.com/" target="_blank">
                            <i class="fa-brands fa-instagram"></i>
                        </a>
                    </li>
                    <li>
                        <a href="https://in.pinterest.com/" target="_blank">
                            <i class="fa-brands fa-pinterest-p"></i>
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</footer>

templates/web/partials/header.html
{% load static %}

<header class="pb-md-4 pb-0">
    <div class="header-top">
        <div class="container-fluid-lg">
            <div class="row">
            </div>
        </div>
    </div>

    <div class="top-nav top-header sticky-header">
        <div class="container-fluid-lg">
            <div class="row">
                <div class="col-12">
                    <div class="navbar-top">
                        <!-- <button class="navbar-toggler d-xl-none d-inline navbar-menu-button" type="button"
                            data-bs-toggle="offcanvas" data-bs-target="#primaryMenu">
                            <span class="navbar-toggler-icon">
                                <i class="fa-solid fa-bars"></i>
                            </span>
                        </button> -->
                        <a href="/" class="web-logo nav-logo">
                            <img src="{% static 'web/images_new/my-gadget.png' %}"
                                class="img-fluid blur-up lazyload" alt="">
                        </a>

                        <div class="middle-box">

                            {% comment %} instead of location all categories {% endcomment %}
                            <div class="header-nav">
                                <div class="header-nav-left">
                                    <button class="dropdown-category">
                                        <i data-feather="align-left"></i>
                                        <span>All Categories</span>
                                    </button>
        
                                    <div class="category-dropdown">
                                    <div class="category-title">
                                        <h5>Categories</h5>
                                        <button type="button" class="btn p-0 close-button text-content">
                                            <i class="fa-solid fa-xmark"></i>
                                        </button>
                                    </div>
        
                                    <ul class="category-list food-menu-filter">
                                       {% for category in categories %}
                                        <li class="onhover-category-list">
                                            <a href="{{category.get_absolute_url}}" class="category-name">
                                                <img src="{{category.image.url}}" alt="">
                                                <h6>{{category.category}}</h6>
                                                <i class="fa-solid fa-angle-right"></i>
                                            </a>         
                                            <div class="onhover-category-box w-100 product-items">
                                                <div class="list-1">
                                                    
                                                    <ul>
                                                        {% for subcategory in category.get_subcategories %}

                                                        <li>
                                                            <a href="{% url 'user:shop_category' subcategory.id %}">{{subcategory.subcategory }}</a>
                                                        </li>

                                                        {% endfor %}    
                                                    </ul>
                                                    
                                                </div>
                                            </div>
                                        </li>
                                        {% endfor %}
                                    </ul>
                                    </div>
                                </div>
                            </div>
                            {% comment %} end  all categories {% endcomment %}

                            <div class="search-box">
                                <form method="GET" action="{% url 'user:search' %}">
                                    <div class="input-group">
                                        <input type="text" class="form-control" placeholder="I'm searching for..."
                                        aria-label="Recipient's username" aria-describedby="button-addon2" name="search"required>
                                        <button class="btn" type="submit" id="button-addon2">
                                            <i data-feather="search"></i>
                                        </button>
                                    </div>
                                </form>
                            </div>
                        </div>

                        <div class="rightside-box">
                           
                            <ul class="right-side-menu">
                                <li class="right-side">
                                    <div class="delivery-login-box">
                                        <div class="delivery-icon">
                                            <div class="search-box">
                                                <i data-feather="search"></i>
                                            </div>
                                        </div>
                                    </div>
                                </li> 
                             
                                <li class="right-side">
                                    <a href="{%url 'user:viewwishlist' %}" class="btn p-0 position-relative header-wishlist">
                                        <i data-feather="heart"></i>
                                    </a>
                                </li>
                                <li class="right-side">
                                    <a href="{%url 'user:viewcart' %}" class="btn p-0 position-relative header-wishlist">
                                        <i data-feather="shopping-cart"></i>
                                    </a>
                                </li>
                                 <li class="right-side onhover-dropdown">
                                    
                                    <div class="delivery-login-box">
                                        <div class="delivery-icon">
                                            <i data-feather="user"></i>
                                        </div>
                                        <div class="delivery-detail">
                                            <h6>Hello,</h6>
                                            <h5>My Account</h5>
                                        </div>
                                    </div>
                                   
                                    <div class="onhover-div onhover-div-login">
                                         <ul class="user-box-name">
                                           
                                            {% if status == 0 %}
                                            <li class="product-box-contain">
                                                <i></i>
                                                <a href={% url 'user:login' %}>Log In</a>
                                            </li>
                                            <li class="product-box-contain">
                                                <a href={% url 'user:sign_up' %}>Register</a>
                                            </li>
                                            {% else %}
                                            <li class="product-box-contain">
                                                <a href={% url 'user:sign_up' %}>New Account</a>
                                            </li>
                                            <li class="product-box-contain">
                                                <a href={% url 'user:logout' %}>Logout</a>
                                            </li>
                                            {% endif %}
                                        </ul> 
                                    </div>
                                   
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% comment %} phone categories {% endcomment %}
    <div class="container-fluid-lg">
        <div class="row">
            <div class="col-12">
                <div class="header-nav">
                   <div class="header-nav-left">
                        <div class="category-dropdown">
                            <div class="category-title">
                                <h5>Categories</h5>
                                <button type="button" class="btn p-0 close-button text-content">
                                    <i class="fa-solid fa-xmark"></i>
                                </button>
                            </div>

                            <ul class="category-list">
                                <li class="onhover-category-list">
                                    {% for category in categories %}
                                    <a href="{{category.get_absolute_url}}" class="category-name">
                                        <img src="{{category.image.url}}"
                                            alt="">
                                        <h6>{{category.category}}</h6>
                                        <i class="fa-solid fa-angle-right"></i>
                                    </a>
                                    <div class="onhover-category-box">
                                        {% for subcategory in category.get_subcategories %}
                                            <div class="category-title-box">
                                                <a href="{% url 'user:shop_category' subcategory.id %}"><h5>{{subcategory.subcategory}}</h5></a>
                                            </div>
                                            {% comment %} <ul>
                                                {% for products in subcategory.get_products %}
                                                <li>
                                                    <a href="{% url 'user:product' products.id %}">{{products.product}}</a>
                                                </li>
                                                {% endfor %}
                                            </ul> {% endcomment %}
                                        {% endfor %}
                                    </div>
                                    {% endfor %}
                                </li>
                            </ul>
                        </div>
                    </div> 

                    <div class="header-nav-middle">
                        <div class="main-nav navbar navbar-expand-xl navbar-light navbar-sticky">
                            <div class="offcanvas offcanvas-collapse order-xl-2" id="primaryMenu">
                                <div class="offcanvas-header navbar-shadow">
                                    <h5>Menu</h5>
                                    <button class="btn-close lead" type="button" data-bs-dismiss="offcanvas"
                                        aria-label="Close"></button>
                                </div>
                          
                            </div>
                        </div>
                    </div>

                    
                </div>
            </div>
        </div>
    </div>
</header>
{% block js %}

{% endblock %}